### PR TITLE
OGC API Features Part 1: Core

### PR DESCRIPTION
**Pull request by ideas-into-software**
### OGC API Features standard

The "OGC API Features" standard consists of multiple parts, including: 

 - "Part 1: Core" (https://docs.ogc.org/is/17-069r4/17-069r4.html)
 - "Part 2: Coordinate Reference Systems by Reference" (https://docs.ogc.org/is/18-058r1/18-058r1.html)
 - "Part 3: Filtering and Common Query Language (CQL)" (https://portal.ogc.org/files/96288)
 - "Part 4: Create, Replace, Update and Delete": https://docs.ogc.org/DRAFTS/20-002.html

As agreed, this implementation initially focuses on "Part 1: Core", then "Part 3: Filtering and Common Query Language (CQL)".

### Implementation

This PR contains implementation of "Part 1: Core" of the "OGC API Features" standard, consisting of model, service layer, integration tests and REST API endpoints.

#### Model

- "OGC API Features" model was initially generated off XSD schema found in the official "OGC API Features" repository (https://github.com/opengeospatial/ogcapi-features/blob/master/core/xml/core.xsd);

- As can be seen in the XSD schema itself, original "OGC API Features" model does not include and lacks any direct connection with "GeoJSON" model (`FeatureCollection`, `Feature`, `Geometry`, etc.); however, it does include "Atom" model, where `Link` type is defined;

- That is why, in this initial implementation, there are three separate model bundles (`de.jena.ogc_features.model.core`, `de.jena.ogc_features.model.geojson` and `de.jena.ogc_features.model.atom`), i.e.: 

  * `de.jena.ogc_features.model.core` - contains "OGC API Features" model initially generated off XSD schema (https://github.com/opengeospatial/ogcapi-features/blob/master/core/xml/core.xsd), then heavily modified, including fixing issues with types created during ECORE model generation, adding ID fields, consistency issues, renaming types and attributes, removing obsolete types, etc.;
  * `de.jena.ogc_features.model.geojson` - contains "GeoJSON" model, initially based on the latest version of "GeoJSON" model from the "PlayerTour" project, augmented / modified  to incorporate insights gathered during the course of work on a recent project, i.e. solving problems with Swagger / OpenAPI GeoJSON support in REST API endpoints utilizing generated EMF model code (https://github.com/AmateurPlayerTour/backend/pull/28); subsequently modified to include ID fields, links, etc.;
  * `de.jena.ogc_features.model.atom` - contains model created while generating initial version of `de.jena.ogc_features.model.core` off XSD schema (https://github.com/opengeospatial/ogcapi-features/blob/master/core/xml/core.xsd), as it includes "Atom" XSD, used for links; this model is shared between `de.jena.ogc_features.model.core` and `de.jena.ogc_features.model.geojson`;

#### REST API endpoints

Following REST API endpoints are implemented:

 - `GET /collections` - returning list of available "OGC API Features" collections;
 
 - `GET /collections/{collectionId}` - returning specific "OGC API Features" collection;
 
 - `GET /collections/{collectionId}/items` - returning "GeoJSON" `FeatureCollection`, present in a given "OGC API Features" collection, with optional `bbox` query parameter (i.e. `GET /collections/{collectionId}/items?bbox={bbox}`);

 - `GET /collections/{collectionId}/items/{featureId}` - returning specific "GeoJSON" `Feature`, present in a given "GeoJSON" `FeatureCollection` / "OGC API Features" collection;

 - `GET /conformance` - returning conformance declaration, i.e. information about conformance classes implemented;
 
 - `GET /` - returning "landing page", consisting of links to main REST API endpoints (entry points);

 - `GET /api` ("API Resource") - returning OpenAPI definition of REST API endpoints and model used;

#### Service layer

Most significant part of the service layer is Lucene spatial search, which will be expanded upon when implementing "Part 3: Filtering and Common Query Language (CQL)" of the "OGC API Features" standard.

All "GeoJSON" model geometry types (`Point`, `LineString`, `Polygon`, `MultiPoint`, `MultiLineString` and `MultiPolygon`) are supported.

### Existing solutions 

To facilitate better understanding of the "OGC API Features" standard based on actual implementations, public demos of the following open-source projects where explored :

 - Public demo of "Hakunapi OGC API Features Server" (https://github.com/nlsfi/hakunapi): https://beta-paikkatieto.maanmittauslaitos.fi/inspire-addresses/features/v1/?f=json

 - Public demo of "ldproxy" (https://github.com/interactive-instruments/ldproxy): https://demo.ldproxy.net/?f=json

### Serialization of enum default values

Serialization of enum default values does not work, which results in incorrectly formed JSON document when EMF EObject is serialized. 

This problem can be observed in 3 types defined in the "GeoJSON" model (`de.jena.ogc_features.model.geojson`), despite having specified their "Default Value Literals", i.e.:

 - `net.opengis.ogcapi.features.conf.geojson.FeatureCollection` defines `type` attribute using `FeatureCollectionType` enum, with "Default Value Literal" being set to "FeatureCollection";
 - `net.opengis.ogcapi.features.conf.geojson.Feature` defines `type` attribute using `FeatureType` enum, with "Default Value Literal" being set to "Feature";
 - `net.opengis.ogcapi.features.conf.geojson.Geometry` defines `type` attribute using `GeometryType` enum, with "Default Value Literal" being set to "Point";

### Saving two-dimensional array data types to MongoDB

Saving two-dimensional array data type to MongoDB causes exception being thrown - full stack below. 

Problem can be observed in `de.jena.ogc_features.service.tests.helper.CollectionsServiceTestHelper.createExtent(String)` method, having commented back in `net.opengis.ogcapi.features.core.SpatialExtent.setBbox(Double[][])` setter method.

```
java.lang.IllegalStateException: Error while encoding EObject. Cause is: writeStartArray can only be called when State is VALUE, not when State is NAME
	at org.gecko.emf.mongo.codecs.EObjectCollectibleCodec.encode(EObjectCollectibleCodec.java:73)
	at org.gecko.emf.mongo.codecs.EObjectCollectibleCodec.encode(EObjectCollectibleCodec.java:43)
	at org.bson.internal.LazyCodec.encode(LazyCodec.java:38)
	at org.bson.codecs.EncoderContext.encodeWithChildContext(EncoderContext.java:91)
	at org.gecko.emf.mongo.codecs.builder.DBObjectBuilderImpl.buildReferencedObject(DBObjectBuilderImpl.java:415)
	at org.gecko.emf.mongo.codecs.builder.DBObjectBuilderImpl.buildReference(DBObjectBuilderImpl.java:380)
	at org.gecko.emf.mongo.codecs.builder.DBObjectBuilderImpl.buildDBObject(DBObjectBuilderImpl.java:192)
	at org.gecko.emf.mongo.codecs.EObjectCollectibleCodec.encode(EObjectCollectibleCodec.java:67)
	at org.gecko.emf.mongo.codecs.EObjectCollectibleCodec.encode(EObjectCollectibleCodec.java:43)
	at org.bson.internal.LazyCodec.encode(LazyCodec.java:38)
	at org.bson.codecs.EncoderContext.encodeWithChildContext(EncoderContext.java:91)
	at org.gecko.emf.mongo.codecs.builder.DBObjectBuilderImpl.buildReferencedObject(DBObjectBuilderImpl.java:415)
	at org.gecko.emf.mongo.codecs.builder.DBObjectBuilderImpl.buildReference(DBObjectBuilderImpl.java:380)
	at org.gecko.emf.mongo.codecs.builder.DBObjectBuilderImpl.buildDBObject(DBObjectBuilderImpl.java:192)
	at org.gecko.emf.mongo.codecs.EObjectCollectibleCodec.encode(EObjectCollectibleCodec.java:67)
	at org.gecko.emf.mongo.codecs.EObjectCollectibleCodec.encode(EObjectCollectibleCodec.java:43)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29)
	at org.bson.codecs.EncoderContext.encodeWithChildContext(EncoderContext.java:91)
	at org.bson.codecs.BsonDocumentCodec.writeValue(BsonDocumentCodec.java:136)
	at org.bson.codecs.BsonDocumentCodec.encode(BsonDocumentCodec.java:115)
	at org.bson.codecs.BsonDocumentCodec.encode(BsonDocumentCodec.java:41)
	at com.mongodb.internal.connection.RequestMessage.addDocument(RequestMessage.java:238)
	at com.mongodb.internal.connection.RequestMessage.addDocument(RequestMessage.java:188)
	at com.mongodb.internal.connection.CommandMessage.encodeMessageBodyWithMetadata(CommandMessage.java:140)
	at com.mongodb.internal.connection.RequestMessage.encode(RequestMessage.java:138)
	at com.mongodb.internal.connection.CommandMessage.encode(CommandMessage.java:61)
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:247)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:99)
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:450)
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:72)
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:226)
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:269)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:131)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:123)
	at com.mongodb.operation.CommandOperationHelper$13.call(CommandOperationHelper.java:710)
	at com.mongodb.operation.OperationHelper.withReleasableConnection(OperationHelper.java:501)
	at com.mongodb.operation.CommandOperationHelper.executeRetryableCommand(CommandOperationHelper.java:703)
	at com.mongodb.operation.CommandOperationHelper.executeRetryableCommand(CommandOperationHelper.java:695)
	at com.mongodb.operation.BaseFindAndModifyOperation.execute(BaseFindAndModifyOperation.java:70)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:216)
	at com.mongodb.client.internal.MongoCollectionImpl.executeFindOneAndReplace(MongoCollectionImpl.java:765)
	at com.mongodb.client.internal.MongoCollectionImpl.findOneAndReplace(MongoCollectionImpl.java:745)
	at org.gecko.emf.mongo.streams.MongoOutputStream.saveSingleObject(MongoOutputStream.java:232)
	at org.gecko.emf.mongo.streams.MongoOutputStream.close(MongoOutputStream.java:143)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.save(ResourceImpl.java:1048)
	at org.gecko.emf.repository.DefaultEMFRepository.save(DefaultEMFRepository.java:189)
	at org.gecko.emf.repository.DefaultEMFRepository.save(DefaultEMFRepository.java:253)
	at org.gecko.emf.repository.DefaultEMFRepository.save(DefaultEMFRepository.java:262)
	at de.jena.ogc_features.service.tests.CollectionsServiceTest.setup(CollectionsServiceTest.java:287)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at aQute.tester.bundle.engine.BundleDescriptor.executeChild(BundleDescriptor.java:49)
	at aQute.tester.bundle.engine.BundleEngine.lambda$executeBundle$7(BundleEngine.java:120)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at aQute.tester.bundle.engine.BundleEngine.executeBundle(BundleEngine.java:120)
	at aQute.tester.bundle.engine.BundleEngine.lambda$execute$5(BundleEngine.java:100)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at aQute.tester.bundle.engine.BundleEngine.execute(BundleEngine.java:100)
Caused by: org.bson.BsonInvalidOperationException: writeStartArray can only be called when State is VALUE, not when State is NAME
	at org.bson.AbstractBsonWriter.throwInvalidState(AbstractBsonWriter.java:744)
	at org.bson.AbstractBsonWriter.checkPreconditions(AbstractBsonWriter.java:699)
	at org.bson.AbstractBsonWriter.writeStartArray(AbstractBsonWriter.java:322)
	at com.mongodb.internal.connection.BsonWriterDecorator.writeStartArray(BsonWriterDecorator.java:63)
	at org.gecko.emf.mongo.codecs.builder.DBObjectBuilderImpl.writePrimitiveValue(DBObjectBuilderImpl.java:516)
	at org.gecko.emf.mongo.codecs.builder.DBObjectBuilderImpl.buildAttributeValue(DBObjectBuilderImpl.java:308)
	at org.gecko.emf.mongo.codecs.builder.DBObjectBuilderImpl.buildAttribute(DBObjectBuilderImpl.java:266)
	at org.gecko.emf.mongo.codecs.builder.DBObjectBuilderImpl.buildDBObject(DBObjectBuilderImpl.java:182)
	at org.gecko.emf.mongo.codecs.EObjectCollectibleCodec.encode(EObjectCollectibleCodec.java:67)
	... 78 more
```

### Should "GeoJSON" model be linked with and "contained" by "OGC API Features" model ? 

Specifically, should `net.opengis.ogcapi.features.core.OGCAPIFeaturesCollection` reference `net.opengis.ogcapi.features.conf.geojson.FeatureCollection` and contain it, so only `OGCAPIFeaturesCollection` is saved to MongoDB ?

For more details, please refer to "Implementation: Model" section of this document.

### Can query consist of columns for both container and contained ?

As can be seen currently in `de.jena.ogc_features.service.impl.CollectionsServiceImpl.getItem(String, String, String, String)` method, `FeatureCollection` is queried, then features it contains are processed separately. 

Instead, is it possible to specify in the `org.gecko.emf.repository.query.IQuery` column and ID value of both container (`GeoJSONPackage.Literals.FEATURE_COLLECTION__ID`) and contained (`GeoJSONPackage.Literals.FEATURE__ID`) ?

If so, then `net.opengis.ogcapi.features.conf.geojson.Feature` could be retrieved directly via `org.gecko.emf.repository.query.QueryRepository.getEObjectByQuery(EClass, IQuery, Map<Object, Object>)`.

### Does Gecko EMF Push Stream Provider (`EPushStreamProvider`) support creating push streams for contained collections ?

Similar to earlier question, but pertaining to PushStreams. 

Currently, in `de.jena.ogc_features.service.impl.FeatureIndexServiceImpl.initializeIndex()` method, non-PushStream version is used, as it's the `net.opengis.ogcapi.features.conf.geojson.Feature` (contained), not `net.opengis.ogcapi.features.conf.geojson.FeatureCollection` (container) which needs to be indexed.

It would obviously be preferable to use PushStreams instead, if such scenario is possible.

### Which sub-sets of "Common Query Language" (CQL2) should be implemented ?
 
As part of requirements gathering phase, it was established that "Part 1: Core" (https://docs.ogc.org/is/17-069r4/17-069r4.html) and "Part 3: Filtering and the Common Query Language (CQL)" (https://portal.ogc.org/files/96288) of "OGC API Features" standard needs to be implemented.

What is not clear is which sub-sets of "CQL" should be implemented ? For a quick overview of "CQL2" sub-sets ("conformance classes" / "requirements classes") see: diagram @ https://github.com/opengeospatial/ogcapi-features/blob/master/cql2/README.md, also https://github.com/opengeospatial/ogcapi-features/blob/master/cql2/standard/clause_2_conformance.adoc

### Should SOAP API, in addition to already implemented REST API, be implemented now or after "Part 3: CQL" is ready ?

As part of requirements gathering phase, it was mentioned that, in addition to REST API, SOAP API should also be implemented. Should SOAP API be implemented now, or after "Part 3: CQL" is ready ?

## More information

 - "OGC API - Features - Overview": https://ogcapi.ogc.org/features/overview.html

 - "OGC API - Features - Part 1: Core corrigendum": https://docs.ogc.org/is/17-069r4/17-069r4.html
 
 - "OGC API - Features - Part 2: Coordinate Reference Systems by Reference corrigendum": https://docs.ogc.org/is/18-058r1/18-058r1.html

 - "OGC API - Features - Part 3: Filtering and the Common Query Language (CQL)": https://portal.ogc.org/files/96288

 - "OGC API - Features - Part 4: Create, Replace, Update and Delete": https://docs.ogc.org/DRAFTS/20-002.html

### CODE REVIEW

**Comment by juergen-albert** [comment]
> Saving two-dimensional array data types to MongoDB

https://github.com/geckoprojects-org/org.gecko.emf.persistence/issues/25

Please create a PR with a fix for this issue.

**Comment by juergen-albert** [comment]
> Serialization of enum default values

You can use 
https://github.com/geckoprojects-org/org.gecko.emf.utils/blob/882fadaba653c565d0c5e58c5a672ec0c23783ad/org.gecko.emf.json/src/org/gecko/emf/json/constants/EMFJs.java#L46 

to trigger serialization of Default Values

**Comment by juergen-albert** [comment]
> Should SOAP API, in addition to already implemented REST API, be implemented now or after "Part 3: CQL" is ready ?

Talked to Stefan: No implementation of SOAP now or after.

**Comment by juergen-albert** [comment]
>Should "GeoJSON" model be linked with and "contained" by "OGC API Features" model ?

I'd say yes. As a general rule for containment, we look at something and can only be associated with only one object.. The Object arm or leg can only be attached to one body.  Thus this reference would be contained. I guess the same applies to the concrete reference you point to.

So, to conclude: GeoJSON should reside in its own ecore, as we plan to reuse it. References in other Models to any GeoJSON Model, should be marked as contained.

**Comment by juergen-albert** [comment]
> Does Gecko EMF Push Stream Provider (EPushStreamProvider) support creating push streams for contained collections ?

I'm not 100% sure if I understood correctly. I understood: In mongo you have a collection FeatureCollection. A FeatureCollection  object can have one ore more Features. You to get a PushStream that only iterates over the contained Features.

If this assumption is correct, then no this is not possible. We only provide a PushStream of Root Objects of a collection. You would need to work with flatMap in such a case, as an intermediate step.

**Comment by juergen-albert** [comment]
> Can query consist of columns for both container and contained 

In Mongo (or at least in the way we use it), you can only create Queries on contained Objects. If you need something similar to a joined Query in SQL, we typically use a Luceneindex for such cases.

**Comment by juergen-albert** [comment]
> Which sub-sets of "Common Query Language" (CQL2) should be implemented ?

None for now. We will need to expand the set, as usecases arise.

**Comment by ideas-into-software** [comment]
@juergen-albert

Having added pagination and fixed issues mentioned earlier, plus 2 other which I noticed, this PR is now marked as ready for review.

Please be aware, that, because of https://github.com/geckoprojects-org/org.gecko.emf.persistence/issues/25, there are PRs opened in projects this project depends on, i.e.: 

- https://github.com/geckoprojects-org/org.gecko.emf.persistence/pull/26
 
- https://github.com/geckoprojects-org/org.gecko.emf/pull/50 (transitively via 'org.gecko.emf.persistence')


Until those are merged and released to Maven Central, I temporarily included latest version of `org.gecko.emf.mongo.component` in this project.

**Comment by ideas-into-software** [comment]
@juergen-albert

Since most metadata-related issues in https://github.com/geckoprojects-org/org.gecko.emf/ and https://github.com/geckoprojects-org/org.gecko.emf.persistence/ projects were apparently solved in the meantime while I was working on other projects, I am re-submiting fix for "Saving two-dimensional array data types to MongoDB" issue ( commit https://github.com/de-jena/ogc-features/pull/1/commits/901cf99c7a6183008c60aaaae3eed7dc041330ae ), which takes into account latest state of these dependent projects.

Once PR https://github.com/geckoprojects-org/org.gecko.emf.persistence/pull/27 is merged and new version of `org.gecko.emf.mongo.component`, which includes code in that PR, released, local repository version of `org.gecko.emf.mongo.component` can be removed. 

Code in this PR ( https://github.com/de-jena/ogc-features/pull/1 ) however is fully functional regardless.

**Comment by juergen-albert** [comment]
Thanks heaps. We will start using it in anger soon and then we will see if it might require further modifications. 

When https://github.com/geckoprojects-org/org.gecko.emf.persistence/pull/27 is merged, we can create another PR to remove the custom version of the org.gecko.emf.mongo.component bundle.

**Pull request merged**
